/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BuildingCreateNestedManyWithoutPollsInput } from "./BuildingCreateNestedManyWithoutPollsInput";
import {
  ValidateNested,
  IsOptional,
  IsJSON,
  IsString,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumPollPollType } from "./EnumPollPollType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class PollCreateInput {
  @ApiProperty({
    required: true,
    type: () => BuildingCreateNestedManyWithoutPollsInput,
  })
  @ValidateNested()
  @Type(() => BuildingCreateNestedManyWithoutPollsInput)
  @IsOptional()
  @Field(() => BuildingCreateNestedManyWithoutPollsInput, {
    nullable: true,
  })
  buildings?: BuildingCreateNestedManyWithoutPollsInput;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSONObject)
  content!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    enum: EnumPollPollType,
  })
  @IsEnum(EnumPollPollType)
  @Field(() => EnumPollPollType)
  pollType!: "General" | "Maintenance" | "Committee";

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  user!: UserWhereUniqueInput;
}
export { PollCreateInput };
