/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePollArgs } from "./CreatePollArgs";
import { UpdatePollArgs } from "./UpdatePollArgs";
import { DeletePollArgs } from "./DeletePollArgs";
import { PollFindManyArgs } from "./PollFindManyArgs";
import { PollFindUniqueArgs } from "./PollFindUniqueArgs";
import { Poll } from "./Poll";
import { BuildingFindManyArgs } from "../../building/base/BuildingFindManyArgs";
import { Building } from "../../building/base/Building";
import { User } from "../../user/base/User";
import { PollService } from "../poll.service";

@graphql.Resolver(() => Poll)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PollResolverBase {
  constructor(
    protected readonly service: PollService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "any",
  })
  async _pollsMeta(
    @graphql.Args() args: PollFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Poll])
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "any",
  })
  async polls(@graphql.Args() args: PollFindManyArgs): Promise<Poll[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Poll, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "own",
  })
  async poll(@graphql.Args() args: PollFindUniqueArgs): Promise<Poll | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "create",
    possession: "any",
  })
  async createPoll(@graphql.Args() args: CreatePollArgs): Promise<Poll> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "update",
    possession: "any",
  })
  async updatePoll(@graphql.Args() args: UpdatePollArgs): Promise<Poll | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "delete",
    possession: "any",
  })
  async deletePoll(@graphql.Args() args: DeletePollArgs): Promise<Poll | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Building])
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "read",
    possession: "any",
  })
  async buildings(
    @graphql.Parent() parent: Poll,
    @graphql.Args() args: BuildingFindManyArgs
  ): Promise<Building[]> {
    const results = await this.service.findBuildings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async user(@graphql.Parent() parent: Poll): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
