/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateMaintenanceArgs } from "./CreateMaintenanceArgs";
import { UpdateMaintenanceArgs } from "./UpdateMaintenanceArgs";
import { DeleteMaintenanceArgs } from "./DeleteMaintenanceArgs";
import { MaintenanceFindManyArgs } from "./MaintenanceFindManyArgs";
import { MaintenanceFindUniqueArgs } from "./MaintenanceFindUniqueArgs";
import { Maintenance } from "./Maintenance";
import { MaintenanceService } from "../maintenance.service";

@graphql.Resolver(() => Maintenance)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MaintenanceResolverBase {
  constructor(
    protected readonly service: MaintenanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "any",
  })
  async _maintenancesMeta(
    @graphql.Args() args: MaintenanceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Maintenance])
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "any",
  })
  async maintenances(
    @graphql.Args() args: MaintenanceFindManyArgs
  ): Promise<Maintenance[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Maintenance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "read",
    possession: "own",
  })
  async maintenance(
    @graphql.Args() args: MaintenanceFindUniqueArgs
  ): Promise<Maintenance | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Maintenance)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "create",
    possession: "any",
  })
  async createMaintenance(
    @graphql.Args() args: CreateMaintenanceArgs
  ): Promise<Maintenance> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Maintenance)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "update",
    possession: "any",
  })
  async updateMaintenance(
    @graphql.Args() args: UpdateMaintenanceArgs
  ): Promise<Maintenance | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Maintenance)
  @nestAccessControl.UseRoles({
    resource: "Maintenance",
    action: "delete",
    possession: "any",
  })
  async deleteMaintenance(
    @graphql.Args() args: DeleteMaintenanceArgs
  ): Promise<Maintenance | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
