/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Building,
  Company,
  Message,
  Poll,
  Report,
  BulletinBoard,
  City,
} from "@prisma/client";

export class BuildingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.BuildingFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingFindManyArgs>
  ): Promise<number> {
    return this.prisma.building.count(args);
  }

  async findMany<T extends Prisma.BuildingFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingFindManyArgs>
  ): Promise<Building[]> {
    return this.prisma.building.findMany(args);
  }
  async findOne<T extends Prisma.BuildingFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingFindUniqueArgs>
  ): Promise<Building | null> {
    return this.prisma.building.findUnique(args);
  }
  async create<T extends Prisma.BuildingCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingCreateArgs>
  ): Promise<Building> {
    return this.prisma.building.create<T>(args);
  }
  async update<T extends Prisma.BuildingUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingUpdateArgs>
  ): Promise<Building> {
    return this.prisma.building.update<T>(args);
  }
  async delete<T extends Prisma.BuildingDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.BuildingDeleteArgs>
  ): Promise<Building> {
    return this.prisma.building.delete(args);
  }

  async findCompanies(
    parentId: string,
    args: Prisma.CompanyFindManyArgs
  ): Promise<Company[]> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .companies(args);
  }

  async findMessage(
    parentId: string,
    args: Prisma.MessageFindManyArgs
  ): Promise<Message[]> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .message(args);
  }

  async findPoll(
    parentId: string,
    args: Prisma.PollFindManyArgs
  ): Promise<Poll[]> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .poll(args);
  }

  async findReports(
    parentId: string,
    args: Prisma.ReportFindManyArgs
  ): Promise<Report[]> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .reports(args);
  }

  async getBulletinBoard(parentId: string): Promise<BulletinBoard | null> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .bulletinBoard();
  }

  async getCity(parentId: string): Promise<City | null> {
    return this.prisma.building
      .findUnique({
        where: { id: parentId },
      })
      .city();
  }
}
