/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BuildingListRelationFilter } from "../../building/base/BuildingListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { BulletinBoardWhereUniqueInput } from "../../bulletinBoard/base/BulletinBoardWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class MessageWhereInput {
  @ApiProperty({
    required: false,
    type: () => BuildingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BuildingListRelationFilter)
  @IsOptional()
  @Field(() => BuildingListRelationFilter, {
    nullable: true,
  })
  buildings?: BuildingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => BulletinBoardWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BulletinBoardWhereUniqueInput)
  @IsOptional()
  @Field(() => BulletinBoardWhereUniqueInput, {
    nullable: true,
  })
  bulletinBoard?: BulletinBoardWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}
export { MessageWhereInput };
